trigger:
  branches:
    include:
      - develop
      - release/*
      - master
resources:
  repositories:
  - repository: azure-pipelines-templates
    type: github
    endpoint: FaganSC
    name: FaganSC/azure-pipelines-templates
    ref: develop
variables:
  node_version: '10.x'
  package_manager: 'npm'
  majorminor: '1.0.0'
  patch: $[counter(${{ variables.majorminor }}, 0)]
  version: $(majorminor).$(patch)
name: ${{ variables.version }}
stages:
- stage: Build
  jobs:
    - template: spfx/build.yml@azure-pipelines-templates
- stage: Test
  dependsOn: 
    - Build
  jobs:
    - template: spfx/test.yml@azure-pipelines-templates
      parameters:
        working_directory: 
        package_manager: ${{ variables.package_manager }}
        node_version: ${{ variables.node_version }}
- stage: GitHubPreRelease
  displayName: GitHub PreRelease
  dependsOn:
    - Test
  jobs:
    - template: spfx/release.yml@azure-pipelines-templates
      parameters:
        release_title: 'Pre-Release $(Build.BuildNumber)'
        target_environment: PreRelease
        gitHubConnection: GitHub
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
        isPreRelease: True
- stage: GitHubRelease
  displayName: GitHub Release
  dependsOn:
    - Test
  jobs:
    - template: spfx/release.yml@azure-pipelines-templates
      parameters:
        release_title: 'Release $(Build.BuildNumber)'
        target_environment: Production
        gitHubConnection: GitHub
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        isPreRelease: False
- stage: Pushlish
  displayName: Pushlish Module to PowerShell Gallery
  dependsOn:
    - Test
  jobs:
    - template: powershell/publish.yml@azure-pipelines-templates
      parameters:
        nugetapikey: ${{ variables.NuGetApiKey }}
        variables_group: DevelopmentTenant
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
